// apps/web/src/lib/ui/RecipeCard.svelte
<script lang="ts">
  import type { RecipeDoc } from '@brewdial/shared';

  interface Props {
    recipe: RecipeDoc;
  }
  let { recipe }: Props = $props();

  function formatDate(iso: string): string {
    if (!iso) return '';
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    return d.toISOString().slice(0, 10);
  }
</script>

<a class="card" href={`/recipes/${recipe.code}`}>
  <p class="card-meta">
    <span class="code">{recipe.code}</span>
    <span class="muted"> · {recipe.method}</span>
  </p>
  <h3 class="card-title">{recipe.title}</h3>
  {#if recipe.beanSnapshot?.name || recipe.beanSnapshot?.roaster || recipe.beanSnapshot?.roastLevel || recipe.beanSnapshot?.origin}
    <p class="card-meta">
      {[
        recipe.beanSnapshot?.name,
        recipe.beanSnapshot?.roaster,
        recipe.beanSnapshot?.roastLevel,
        recipe.beanSnapshot?.origin
      ].filter(Boolean).join(' · ')}
    </p>
  {/if}
  {#if recipe.params?.grinder || recipe.params?.brewer}
    <p class="card-meta muted">
      {[recipe.params?.brewer, recipe.params?.grinder].filter(Boolean).join(' · ')}
    </p>
  {/if}
  <p class="card-meta muted">{formatDate(recipe.createdAt)}</p>
</a>

// apps/miniapp/src/components/RecipeCard.tsx
import type { RecipeDoc } from '../lib/domain';
import { METHOD_LABELS } from '../lib/recipe-presets';

function formatDate(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' });
}

export default function RecipeCard({ recipe }: { recipe: RecipeDoc }) {
  const bean = [
    recipe.beanSnapshot?.name,
    recipe.beanSnapshot?.roaster,
    recipe.beanSnapshot?.roastLevel,
    recipe.beanSnapshot?.origin,
  ]
    .filter(Boolean)
    .join(' · ');
  const gear = [recipe.params?.brewer, recipe.params?.grinder].filter(Boolean).join(' · ');

  return (
    <a className="card" href={`#/recipes/${recipe.code}`}>
      <p className="card-meta">
        <span className="code">{recipe.code}</span>
        <span className="muted">· {METHOD_LABELS[recipe.method]}</span>
        {recipe.createdBy === 'agent' && <span className="badge-ai">✨ AI 생성</span>}
      </p>
      <p className="card-title">{recipe.title}</p>
      {bean && <p className="card-meta">{bean}</p>}
      {gear && <p className="card-meta muted">{gear}</p>}
      <p className="card-meta muted">{formatDate(recipe.createdAt)}</p>
    </a>
  );
}
