// apps/miniapp/src/pages/Home.tsx
import { Button, Top } from '@toss/tds-mobile';
import { useEffect, useState } from 'react';
import { listRecentRecipes } from '../lib/data/recipes';
import type { RecipeDoc } from '../lib/domain';
import RecipeCard from '../components/RecipeCard';

export default function Home() {
  const [recipes, setRecipes] = useState<RecipeDoc[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    listRecentRecipes(100)
      .then(setRecipes)
      .catch((e) => setError((e as Error).message))
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <Top
        title={<Top.TitleParagraph size={28}>다음 브루를 다이얼인 ☕</Top.TitleParagraph>}
        subtitleBottom={
          <Top.SubtitleParagraph size={15}>
            레시피와 추출 타이머, 피드백을 한 곳에서.
          </Top.SubtitleParagraph>
        }
      />
      <div className="screen">
        <div className="row">
          <Button as="a" variant="weak" href="#/recipes/new">
            새 레시피 만들기
          </Button>
        </div>

        {error && <div className="error-panel">불러오기 실패: {error}</div>}

        <section className="stack-tight">
          <h2>레시피{!loading && !error ? ` ${recipes.length}개` : ''}</h2>
          {loading ? (
            <p className="muted">불러오는 중…</p>
          ) : recipes.length === 0 && !error ? (
            <p className="empty">아직 레시피가 없어요. 첫 레시피를 만들어 보세요.</p>
          ) : (
            <div className="stack">
              {recipes.map((r) => (
                <RecipeCard key={r._id} recipe={r} />
              ))}
            </div>
          )}
        </section>
      </div>
    </>
  );
}

// apps/toss/src/pages/Home.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { listRecentRecipes } from '../lib/data/recipes';
  import type { RecipeDoc } from '../lib/domain';
  import RecipeCard from '../lib/ui/RecipeCard.svelte';

  let recipes = $state<RecipeDoc[]>([]);
  let error = $state<string | null>(null);
  let loading = $state(true);

  onMount(async () => {
    try {
      recipes = await listRecentRecipes(5);
    } catch (e) {
      error = (e as Error).message;
    } finally {
      loading = false;
    }
  });
</script>

<section class="stack">
  <div class="stack-tight">
    <h1>다음 브루를 다이얼인 ☕</h1>
    <p class="muted">레시피 · 추출 타이머 · 피드백을 한 곳에서.</p>
  </div>

  <div class="row">
    <a class="btn" href="#/recipes/new">새 레시피</a>
    <a class="btn btn-secondary" href="#/recipes">전체 레시피</a>
  </div>

  {#if error}<div class="error-panel">불러오기 실패: {error}</div>{/if}

  <section class="stack-tight">
    <h2>최근 레시피</h2>
    {#if loading}
      <p class="muted">불러오는 중…</p>
    {:else if recipes.length === 0 && !error}
      <p class="empty">아직 레시피가 없어요. 첫 레시피를 만들어 보세요.</p>
    {:else}
      <div class="stack">
        {#each recipes as recipe (recipe._id)}
          <RecipeCard {recipe} />
        {/each}
      </div>
    {/if}
  </section>
</section>
