// apps/miniapp/src/pages/RecipeDetail.tsx
import { Top } from '@toss/tds-mobile';
import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import {
  buildBrewPhases,
  buildPourSchedule,
  formatSeconds,
  getBrewPhaseProgressRatio,
  getCurrentBrewPhase,
  getExpectedWaterGForPhase,
  isBrewPhaseResting,
  roundToStep,
  type BrewPhase,
} from '../lib/brew-timer/pour-schedule';
import { loadSoundPreference, saveSoundPreference } from '../lib/brew-timer/sound-preference';
import { createPourAudio, type PourAudio } from '../lib/brew-timer/pour-audio';
import { haptic, setKeepAwake } from '../lib/toss';
import { getRecipeByCode } from '../lib/data/recipes';
import { listFeedbackByRecipe } from '../lib/data/feedback';
import FeedbackForm from '../components/FeedbackForm';
import { METHOD_LABELS } from '../lib/recipe-presets';
import { paramLabel, ratingLabel } from '../lib/labels';
import type { FeedbackDoc, RecipeCode, RecipeDoc } from '../lib/domain';

type Tab = 'timer' | 'recipe' | 'feedback';

function formatDateTime(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleString('ko-KR', { dateStyle: 'medium', timeStyle: 'short' });
}

export default function RecipeDetail({ code }: { code: string }) {
  const [recipe, setRecipe] = useState<RecipeDoc | null>(null);
  const [feedback, setFeedback] = useState<FeedbackDoc[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>('timer');

  const [elapsed, setElapsed] = useState(0);
  const [running, setRunning] = useState(false);
  const [soundEnabled, setSoundEnabled] = useState(true);

  const audioRef = useRef<PourAudio | null>(null);
  const runningRef = useRef(false);
  const soundRef = useRef(true);
  const lastAnnouncedRef = useRef(-1);
  const completedRef = useRef(false);
  const totalRef = useRef(0);
  const phasesRef = useRef<BrewPhase[]>([]);

  const schedule = useMemo(
    () => (recipe ? buildPourSchedule(recipe) : { totalSec: 0, phases: [] }),
    [recipe]
  );
  const brewPhases = useMemo(() => (recipe ? buildBrewPhases(recipe) : []), [recipe]);

  useEffect(() => {
    totalRef.current = schedule.totalSec;
    phasesRef.current = brewPhases;
  }, [schedule, brewPhases]);
  useEffect(() => {
    runningRef.current = running;
  }, [running]);

  function announce() {
    void haptic('tickMedium');
    if (soundRef.current) audioRef.current?.playPhaseStart();
  }

  useEffect(() => {
    const pref = loadSoundPreference();
    setSoundEnabled(pref);
    soundRef.current = pref;
    audioRef.current = createPourAudio();

    const id = window.setInterval(() => {
      if (!runningRef.current) return;
      setElapsed((e) => Math.min(e + 1, totalRef.current));
    }, 1000);

    void (async () => {
      try {
        const [r, fb] = await Promise.all([
          getRecipeByCode(code as RecipeCode),
          listFeedbackByRecipe(code as RecipeCode),
        ]);
        if (!r) setLoadError('레시피를 찾을 수 없어요.');
        setRecipe(r);
        setFeedback(fb);
      } catch (e) {
        setLoadError((e as Error).message);
      } finally {
        setLoading(false);
      }
    })();

    return () => {
      window.clearInterval(id);
      void setKeepAwake(false);
      audioRef.current?.close();
      audioRef.current = null;
    };
  }, [code]);

  useEffect(() => {
    if (elapsed > 0) {
      const phase = getCurrentBrewPhase(brewPhases, elapsed);
      if (phase && phase.index !== lastAnnouncedRef.current) {
        lastAnnouncedRef.current = phase.index;
        announce();
      }
    }
    if (schedule.totalSec > 0 && elapsed >= schedule.totalSec && !completedRef.current) {
      completedRef.current = true;
      runningRef.current = false;
      setRunning(false);
      void setKeepAwake(false);
      void haptic('success');
      if (soundRef.current) audioRef.current?.playComplete();
    }
  }, [elapsed, brewPhases, schedule.totalSec]);

  const canUseTimer = schedule.phases.length > 0;
  const currentPhase = getCurrentBrewPhase(brewPhases, elapsed);
  const inRest = currentPhase ? isBrewPhaseResting(currentPhase, elapsed) : false;
  const expectedG = currentPhase ? getExpectedWaterGForPhase(currentPhase, elapsed) : undefined;
  const phasePct = currentPhase
    ? Math.round(getBrewPhaseProgressRatio(currentPhase, elapsed) * 100)
    : 0;
  const isLast = currentPhase != null && currentPhase.index === brewPhases.length - 1;
  const nextPhase = brewPhases.find((p) => p.startSec > elapsed) ?? null;
  const timerDone = canUseTimer && elapsed >= schedule.totalSec;
  const dialProgress = schedule.totalSec > 0 ? Math.min(1, elapsed / schedule.totalSec) : 0;

  function start() {
    if (!canUseTimer) return;
    if (completedRef.current || elapsed >= schedule.totalSec) {
      reset(); // finished → back to start; avoids a frozen fake-running state
      return;
    }
    runningRef.current = true;
    setRunning(true);
    void setKeepAwake(true);
    void audioRef.current?.unlock();
    const phase = getCurrentBrewPhase(brewPhases, elapsed);
    if (phase && !inRest && lastAnnouncedRef.current !== phase.index) {
      lastAnnouncedRef.current = phase.index;
      announce();
    }
  }
  function pause() {
    runningRef.current = false;
    setRunning(false);
    void setKeepAwake(false);
  }
  function reset() {
    runningRef.current = false;
    setRunning(false);
    void setKeepAwake(false);
    setElapsed(0);
    lastAnnouncedRef.current = -1;
    completedRef.current = false;
  }
  function onSound(v: boolean) {
    setSoundEnabled(v);
    soundRef.current = v;
    saveSoundPreference(v);
    if (v) void audioRef.current?.unlock();
  }
  function pourLabel(i: number) {
    return i === 0 ? 'Bloom' : `Pour ${i}`;
  }
  function pourState(p: BrewPhase): string {
    if (elapsed >= p.endSec) return 'done';
    if (elapsed >= p.startSec) return 'now';
    return 'upcoming';
  }
  function phasePill(p: BrewPhase): string {
    if (p.kind === 'bloom') return 'Bloom';
    const before = brewPhases.slice(0, p.index).filter((x) => x.kind === 'pour').length;
    return `Pour ${before + 1}`;
  }

  if (loading) {
    return (
      <div className="screen">
        <p className="muted">불러오는 중…</p>
      </div>
    );
  }
  if (loadError || !recipe) {
    return (
      <div className="screen">
        <div className="error-panel">{loadError ?? '레시피를 찾을 수 없어요.'}</div>
        <a className="card" href="#/recipes">
          레시피 목록으로
        </a>
      </div>
    );
  }

  return (
    <>
      <Top
        title={<Top.TitleParagraph size={22}>{recipe.title}</Top.TitleParagraph>}
        subtitleBottom={
          <Top.SubtitleParagraph size={13}>
            {recipe.code} · {METHOD_LABELS[recipe.method]} · {formatDateTime(recipe.createdAt)}
          </Top.SubtitleParagraph>
        }
      />
      <div className="screen">
        {recipe.createdBy === 'agent' && (
          <p className="card-meta">
            <span className="badge-ai">✨ AI 생성</span>
            <span className="muted">맛을 확인하고 피드백을 남겨주세요.</span>
          </p>
        )}

        <div className="seg" role="tablist" aria-label="레시피 보기">
          <button
            role="tab"
            id="tab-timer"
            aria-selected={tab === 'timer'}
            aria-controls="panel-timer"
            className={tab === 'timer' ? 'active' : undefined}
            onClick={() => setTab('timer')}
          >
            타이머
          </button>
          <button
            role="tab"
            id="tab-recipe"
            aria-selected={tab === 'recipe'}
            aria-controls="panel-recipe"
            className={tab === 'recipe' ? 'active' : undefined}
            onClick={() => setTab('recipe')}
          >
            레시피
          </button>
          <button
            role="tab"
            id="tab-feedback"
            aria-selected={tab === 'feedback'}
            aria-controls="panel-feedback"
            className={tab === 'feedback' ? 'active' : undefined}
            onClick={() => setTab('feedback')}
          >
            피드백
          </button>
        </div>

        {tab === 'timer' &&
          (canUseTimer ? (
            <section
              className="brew-timer"
              role="tabpanel"
              id="panel-timer"
              aria-labelledby="tab-timer"
              aria-label="추출 타이머"
            >
              {currentPhase ? (
                <span className="phase-pill">
                  {phasePill(currentPhase)}
                  {inRest ? ' · 쉬는 중' : ''}
                </span>
              ) : timerDone ? (
                <span className="phase-pill">완료</span>
              ) : null}

              <div className="dial" style={{ '--p': dialProgress } as CSSProperties} role="timer">
                <div className="clock">
                  <div className="time">{formatSeconds(elapsed)}</div>
                  <div className="of">/ {formatSeconds(schedule.totalSec)}</div>
                </div>
              </div>

              <div className="timer-body" aria-live="polite">
                {currentPhase ? (
                  <>
                    <p className="timer-status">
                      {currentPhase.startLabel}–{currentPhase.pourEndLabel} ·{' '}
                      {currentPhase.targetWaterG !== undefined
                        ? `${currentPhase.targetWaterG}g까지`
                        : '목표 무게 미지정'}
                    </p>
                    {inRest ? (
                      <p className="timer-rest">
                        붓기 끝 · {isLast ? '추출 완료까지' : '다음 푸어까지'}{' '}
                        <span className="timer-num">
                          {formatSeconds(currentPhase.endSec - elapsed)}
                        </span>
                      </p>
                    ) : (
                      expectedG !== undefined && (
                        <p className="timer-expected">
                          지금쯤 약 <span className="timer-num">{roundToStep(expectedG)}</span>g
                        </p>
                      )
                    )}
                    {currentPhase.note && <p className="sub">{currentPhase.note}</p>}
                    <div className={`phase-progress${inRest ? ' wait' : ''}`}>
                      <span style={{ width: `${phasePct}%` }} />
                    </div>
                    {nextPhase && !timerDone && (
                      <p className="muted">
                        다음: {nextPhase.startLabel}–{nextPhase.pourEndLabel} ·{' '}
                        {nextPhase.targetWaterG !== undefined
                          ? `${nextPhase.targetWaterG}g까지`
                          : '목표 무게 미지정'}
                      </p>
                    )}
                  </>
                ) : timerDone ? (
                  <p className="timer-status">추출 완료 · 목표 {formatSeconds(schedule.totalSec)}</p>
                ) : null}
              </div>

              <div className="timer-controls">
                {running ? (
                  <button className="t-btn" type="button" onClick={pause}>
                    일시정지
                  </button>
                ) : (
                  <button className="t-btn" type="button" onClick={start}>
                    {elapsed > 0 ? '계속' : '추출 시작'}
                  </button>
                )}
                <button className="t-btn secondary" type="button" onClick={reset}>
                  리셋
                </button>
              </div>
              <label className="sound-toggle">
                <input
                  type="checkbox"
                  checked={soundEnabled}
                  onChange={(e) => onSound(e.target.checked)}
                />
                단계 알림 소리
              </label>
            </section>
          ) : (
            <p className="empty">이 레시피에는 시간이 지정된 푸어가 없어 타이머를 쓸 수 없어요.</p>
          ))}

        {tab === 'recipe' && (
          <div className="stack" role="tabpanel" id="panel-recipe" aria-labelledby="tab-recipe">
            {Object.keys(recipe.params).length > 0 && (
              <section className="stack-tight">
                <h2>파라미터</h2>
                <dl className="dl">
                  {Object.entries(recipe.params).map(([k, v]) => (
                    <div key={k} style={{ display: 'contents' }}>
                      <dt>{paramLabel(k)}</dt>
                      <dd>{String(v)}</dd>
                    </div>
                  ))}
                </dl>
              </section>
            )}
            {brewPhases.length > 0 && (
              <section className="stack-tight">
                <h2>푸어 일정</h2>
                <ul className="pour-list">
                  {brewPhases.map((p) => (
                    <li key={p.index} className={`pour-row ${pourState(p)}`}>
                      <span>{pourLabel(p.index)}</span>
                      <span className="muted">
                        {p.startLabel} – {p.pourEndLabel}
                        {p.pourEndSec < p.endSec && (
                          <span className="detail">
                            쉬기 {p.pourEndLabel} – {p.endLabel}
                          </span>
                        )}
                      </span>
                      <span className="grams">
                        {p.targetWaterG !== undefined ? `${p.targetWaterG} g` : '—'}
                      </span>
                    </li>
                  ))}
                </ul>
              </section>
            )}
            {recipe.steps.length > 0 && (
              <section className="stack-tight">
                <h2>스텝</h2>
                <ol
                  style={{
                    margin: 0,
                    paddingLeft: '1.2rem',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 6,
                  }}
                >
                  {recipe.steps.map((s, i) => (
                    <li key={i}>{s.note}</li>
                  ))}
                </ol>
              </section>
            )}
            {recipe.notes && (
              <section className="stack-tight">
                <h2>메모</h2>
                <p>{recipe.notes}</p>
              </section>
            )}
          </div>
        )}

        {tab === 'feedback' && (
          <section className="stack" role="tabpanel" id="panel-feedback" aria-labelledby="tab-feedback">
            <FeedbackForm
              recipeCode={recipe.code}
              onCreated={(fb) => setFeedback((f) => [fb, ...f])}
            />
            {feedback.length === 0 ? (
              <p className="empty">아직 피드백이 없어요. 첫 피드백을 남겨보세요.</p>
            ) : (
              feedback.map((fb) => (
                <article key={fb._id} className="card">
                  <p className="card-meta muted">{formatDateTime(fb.createdAt)}</p>
                  {fb.ratings && (
                    <dl className="dl">
                      {Object.entries(fb.ratings).map(([k, v]) => (
                        <div key={k} style={{ display: 'contents' }}>
                          <dt>{ratingLabel(k)}</dt>
                          <dd>{String(v)}</dd>
                        </div>
                      ))}
                    </dl>
                  )}
                  {fb.quickTags && fb.quickTags.length > 0 && (
                    <div className="chips">
                      {fb.quickTags.map((t) => (
                        <span key={t} className="chip">
                          {t}
                        </span>
                      ))}
                    </div>
                  )}
                  {fb.comment && <p>{fb.comment}</p>}
                  {fb.rawComment && <p>{fb.rawComment}</p>}
                </article>
              ))
            )}
          </section>
        )}
      </div>
    </>
  );
}

// apps/toss/src/pages/RecipeDetail.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    buildPourSchedule,
    buildBrewPhases,
    formatSeconds,
    getCurrentBrewPhase,
    getExpectedWaterGForPhase,
    getBrewPhaseProgressRatio,
    isBrewPhaseResting,
    roundToStep,
    type BrewPhase
  } from '../lib/brew-timer/pour-schedule';
  import { loadSoundPreference, saveSoundPreference } from '../lib/brew-timer/sound-preference';
  import { createPourAudio, type PourAudio } from '../lib/brew-timer/pour-audio';
  import { haptic } from '../lib/toss';
  import { getRecipeByCode } from '../lib/data/recipes';
  import { listFeedbackByRecipe } from '../lib/data/feedback';
  import type { FeedbackDoc, FeedbackRatings, RecipeCode, RecipeDoc } from '../lib/domain';

  let { code }: { code: string } = $props();

  let recipe = $state<RecipeDoc | null>(null);
  let feedback = $state<FeedbackDoc[]>([]);
  let loading = $state(true);
  let loadError = $state<string | null>(null);

  let elapsedSec = $state(0);
  let isTimerRunning = $state(false);
  let lastAnnouncedPhase = $state(-1);
  let soundEnabled = $state(true);
  let completionAnnounced = $state(false);
  let pourAudio: PourAudio | null = null;

  const pourSchedule = $derived(recipe ? buildPourSchedule(recipe) : { totalSec: 0, phases: [] });
  const brewPhases = $derived(recipe ? buildBrewPhases(recipe) : []);
  const canUseTimer = $derived(pourSchedule.phases.length > 0);

  const currentBrewPhase = $derived(getCurrentBrewPhase(brewPhases, elapsedSec));
  const phaseExpectedG = $derived(
    currentBrewPhase ? getExpectedWaterGForPhase(currentBrewPhase, elapsedSec) : undefined
  );
  const phaseProgressPct = $derived(
    currentBrewPhase ? Math.round(getBrewPhaseProgressRatio(currentBrewPhase, elapsedSec) * 100) : 0
  );
  const inRestTail = $derived(
    currentBrewPhase ? isBrewPhaseResting(currentBrewPhase, elapsedSec) : false
  );
  const isLastBrewPhase = $derived(
    currentBrewPhase !== null && currentBrewPhase.index === brewPhases.length - 1
  );
  const nextPhase = $derived(brewPhases.find((phase) => phase.startSec > elapsedSec) ?? null);
  const timerDone = $derived(canUseTimer && elapsedSec >= pourSchedule.totalSec);
  const dialProgress = $derived(
    pourSchedule.totalSec > 0 ? Math.min(1, elapsedSec / pourSchedule.totalSec) : 0
  );

  function pourLabel(index: number): string {
    return index === 0 ? 'Bloom' : `Pour ${index}`;
  }
  function phasePillLabel(phase: BrewPhase): string {
    if (phase.kind === 'bloom') return 'Bloom';
    const pourCountBefore = brewPhases.slice(0, phase.index).filter((p) => p.kind === 'pour').length;
    return `Pour ${pourCountBefore + 1}`;
  }
  function pourState(phase: { startSec: number; endSec: number }): 'done' | 'now' | 'upcoming' {
    if (elapsedSec >= phase.endSec) return 'done';
    if (elapsedSec >= phase.startSec) return 'now';
    return 'upcoming';
  }
  function formatDate(iso: string): string {
    if (!iso) return '';
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    return d.toISOString().slice(0, 16).replace('T', ' ');
  }
  function targetLabel(grams: number | undefined): string {
    return grams === undefined ? '목표 무게 미지정' : `${grams}g까지`;
  }
  function phaseTitle(phase: BrewPhase): string {
    return `${phase.startLabel}–${phase.pourEndLabel} · ${targetLabel(phase.targetWaterG)}`;
  }
  function ratingPairs(r: FeedbackRatings): [string, unknown][] {
    return Object.entries(r);
  }

  // Phase cue: haptic always fires (works on silent), tone only when enabled.
  function announcePhase(): void {
    void haptic('tickMedium');
    if (soundEnabled) pourAudio?.playPhaseStart();
  }

  function startTimer(): void {
    if (!canUseTimer) return;
    isTimerRunning = true;
    if (pourAudio) void pourAudio.unlock();
    if (currentBrewPhase && !inRestTail && lastAnnouncedPhase !== currentBrewPhase.index) {
      lastAnnouncedPhase = currentBrewPhase.index;
      announcePhase();
    }
  }
  function pauseTimer(): void {
    isTimerRunning = false;
  }
  function resetTimer(): void {
    isTimerRunning = false;
    elapsedSec = 0;
    lastAnnouncedPhase = -1;
    completionAnnounced = false;
  }
  function onSoundToggle(): void {
    saveSoundPreference(soundEnabled);
    if (soundEnabled) void pourAudio?.unlock();
  }
  function testSound(): void {
    void pourAudio?.unlock();
    void haptic('basicMedium');
    if (soundEnabled) pourAudio?.playPhaseStart();
  }

  onMount(() => {
    soundEnabled = loadSoundPreference();
    pourAudio = createPourAudio();

    const id = window.setInterval(() => {
      if (!isTimerRunning) return;
      elapsedSec = Math.min(elapsedSec + 1, pourSchedule.totalSec);
      const phase = getCurrentBrewPhase(brewPhases, elapsedSec);
      if (phase && phase.index !== lastAnnouncedPhase) {
        lastAnnouncedPhase = phase.index;
        announcePhase();
      }
      if (elapsedSec >= pourSchedule.totalSec && !completionAnnounced) {
        isTimerRunning = false;
        completionAnnounced = true;
        void haptic('success');
        if (soundEnabled) pourAudio?.playComplete();
      }
    }, 1000);

    void (async () => {
      try {
        const [r, fb] = await Promise.all([
          getRecipeByCode(code as RecipeCode),
          listFeedbackByRecipe(code as RecipeCode)
        ]);
        if (!r) loadError = '레시피를 찾을 수 없어요.';
        recipe = r;
        feedback = fb;
      } catch (e) {
        loadError = (e as Error).message;
      } finally {
        loading = false;
      }
    })();

    return () => {
      window.clearInterval(id);
      pourAudio?.close();
      pourAudio = null;
    };
  });
</script>

{#if loading}
  <p class="muted">불러오는 중…</p>
{:else if loadError || !recipe}
  <section class="stack">
    <div class="error-panel">{loadError ?? '레시피를 찾을 수 없어요.'}</div>
    <a class="btn btn-secondary" href="#/recipes">레시피 목록</a>
  </section>
{:else}
  <section class="stack">
    <div class="stack-tight">
      <p class="card-meta">
        <span class="code">{recipe.code}</span>
        <span class="muted">· {recipe.method}</span>
        <span class="muted">· {formatDate(recipe.createdAt)}</span>
        {#if recipe.createdBy === 'agent'}<span class="badge-ai">✨ AI 생성</span>{/if}
      </p>
      <h1>{recipe.title}</h1>
      {#if recipe.createdBy === 'agent'}
        <p class="sub">이 레시피는 AI가 생성했어요. 직접 맛을 확인하고 피드백을 남겨주세요.</p>
      {/if}
    </div>

    {#if recipe.beanSnapshot && (recipe.beanSnapshot.name || recipe.beanSnapshot.roaster || recipe.beanSnapshot.origin || recipe.beanSnapshot.process || recipe.beanSnapshot.roastLevel)}
      <section class="stack-tight">
        <h2>원두</h2>
        <dl class="dl">
          {#if recipe.beanSnapshot.name}<dt>이름</dt><dd>{recipe.beanSnapshot.name}</dd>{/if}
          {#if recipe.beanSnapshot.roaster}<dt>로스터</dt><dd>{recipe.beanSnapshot.roaster}</dd>{/if}
          {#if recipe.beanSnapshot.roastLevel}<dt>로스팅</dt><dd>{recipe.beanSnapshot.roastLevel}</dd>{/if}
          {#if recipe.beanSnapshot.origin}<dt>원산지</dt><dd>{recipe.beanSnapshot.origin}</dd>{/if}
          {#if recipe.beanSnapshot.process}<dt>가공</dt><dd>{recipe.beanSnapshot.process}</dd>{/if}
        </dl>
      </section>
    {/if}

    {#if Object.keys(recipe.params).length > 0}
      <section class="stack-tight">
        <h2>파라미터</h2>
        <dl class="dl">
          {#each Object.entries(recipe.params) as [key, value]}
            <dt>{key}</dt><dd>{value}</dd>
          {/each}
        </dl>
      </section>
    {/if}

    {#if canUseTimer}
      <section class="card brew-timer" aria-label="추출 타이머">
        <div class="dial-wrap">
          {#if currentBrewPhase}
            <span class="phase-pill">{phasePillLabel(currentBrewPhase)}{inRestTail ? ' · 쉬는 중' : ''}</span>
          {:else if timerDone}
            <span class="phase-pill">완료</span>
          {/if}
          <div class="dial" style="--dial-progress: {dialProgress}" role="timer" aria-label="추출 경과 시간">
            <div class="clock">
              <div class="time">{formatSeconds(elapsedSec)}</div>
              <div class="of">/ {formatSeconds(pourSchedule.totalSec)}</div>
            </div>
          </div>
        </div>

        <div class="stack-tight">
          {#if currentBrewPhase}
            <p class="timer-status">
              지금: {currentBrewPhase.startLabel}–{currentBrewPhase.pourEndLabel} ·
              {currentBrewPhase.targetWaterG !== undefined ? `${currentBrewPhase.targetWaterG}g까지` : '목표 무게 미지정'}
            </p>
            {#if currentBrewPhase.note}<p class="muted">{currentBrewPhase.note}</p>{/if}
            {#if inRestTail}
              {#if isLastBrewPhase}
                <p class="timer-rest">붓기 끝 · 추출 완료까지 <span class="timer-rest-num">{formatSeconds(currentBrewPhase.endSec - elapsedSec)}</span></p>
              {:else}
                <p class="timer-rest">붓기 끝 · 다음 푸어까지 <span class="timer-rest-num">{formatSeconds(currentBrewPhase.endSec - elapsedSec)}</span></p>
              {/if}
            {:else}
              {#if phaseExpectedG !== undefined}
                <p class="timer-expected">지금쯤 약 <span class="timer-expected-num">{roundToStep(phaseExpectedG)}</span>g</p>
              {/if}
              {#if currentBrewPhase.targetWaterG !== undefined}
                <p class="timer-target muted">목표: {currentBrewPhase.pourEndLabel}까지 {currentBrewPhase.targetWaterG}g</p>
              {/if}
            {/if}
            <div class="phase-progress {inRestTail ? 'phase-kind-wait' : ''}" role="progressbar" aria-valuenow={phaseProgressPct} aria-valuemin="0" aria-valuemax="100" aria-label="현재 구간 진행률">
              <div class="phase-progress-fill" style="width: {phaseProgressPct}%"></div>
            </div>
          {:else if timerDone}
            <p class="timer-status">추출 완료 · 목표 {formatSeconds(pourSchedule.totalSec)}</p>
          {/if}
          {#if nextPhase && !timerDone}
            <p class="muted">다음: {phaseTitle(nextPhase)}</p>
          {/if}
        </div>

        <ul class="pour-list">
          {#each brewPhases as phase (phase.index)}
            <li class="pour-row {pourState(phase)}">
              <span class="label">{pourLabel(phase.index)}</span>
              <span class="time muted">
                {phase.startLabel} – {phase.pourEndLabel}
                {#if phase.pourEndSec < phase.endSec}
                  <span class="time-detail">쉬기 {phase.pourEndLabel} – {phase.endLabel}</span>
                {/if}
              </span>
              <span class="grams">{phase.targetWaterG !== undefined ? `${phase.targetWaterG} g` : '—'}</span>
            </li>
          {/each}
        </ul>

        <div class="row">
          {#if isTimerRunning}
            <button class="btn" type="button" onclick={pauseTimer}>일시정지</button>
          {:else}
            <button class="btn" type="button" onclick={startTimer}>{elapsedSec > 0 ? '계속' : '추출 시작'}</button>
          {/if}
          <button class="btn btn-secondary" type="button" onclick={resetTimer}>리셋</button>
          <label class="sound-toggle">
            <input type="checkbox" bind:checked={soundEnabled} onchange={onSoundToggle} />
            사운드
          </label>
          <button class="btn btn-secondary" type="button" onclick={testSound}>테스트</button>
        </div>
      </section>
    {/if}

    {#if recipe.steps.length > 0}
      <section class="stack-tight">
        <h2>스텝</h2>
        <ol>{#each recipe.steps as step, i (i)}<li>{step.note}</li>{/each}</ol>
      </section>
    {/if}

    {#if recipe.notes}
      <section class="stack-tight"><h2>메모</h2><p>{recipe.notes}</p></section>
    {/if}

    <div><a class="btn" href={`#/feedback/new?recipeCode=${recipe.code}`}>피드백 추가</a></div>

    <section class="stack-tight">
      <h2>피드백</h2>
      {#if feedback.length === 0}
        <p class="muted">아직 피드백이 없어요.</p>
      {:else}
        <div class="stack">
          {#each feedback as fb (fb._id)}
            <article class="card">
              <p class="card-meta muted">{formatDate(fb.createdAt)}</p>
              {#if fb.ratings}
                <dl class="dl">{#each ratingPairs(fb.ratings) as [k, v]}<dt>{k}</dt><dd>{v}</dd>{/each}</dl>
              {/if}
              {#if fb.comment}<p>{fb.comment}</p>{/if}
              {#if fb.rawComment}<p>{fb.rawComment}</p>{/if}
            </article>
          {/each}
        </div>
      {/if}
    </section>
  </section>
{/if}

<style>
  .brew-timer {
    gap: 12px;
    display: flex;
    flex-direction: column;
  }
  .dial-wrap {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
    padding: 4px 0;
  }
  .phase-pill {
    font-size: 0.8rem;
    font-weight: 700;
    color: var(--accent-strong);
    background: var(--accent-soft);
    padding: 4px 10px;
    border-radius: 999px;
  }
  .dial {
    width: 168px;
    height: 168px;
    border-radius: 50%;
    background: conic-gradient(
      var(--accent) calc(var(--dial-progress) * 360deg),
      var(--surface-muted) 0
    );
    display: grid;
    place-items: center;
  }
  .clock {
    width: 132px;
    height: 132px;
    border-radius: 50%;
    background: var(--card);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  .clock .time {
    font-family: var(--font-mono);
    font-variant-numeric: tabular-nums;
    font-size: 2rem;
    font-weight: 700;
  }
  .clock .of {
    color: var(--text-muted);
    font-size: 0.85rem;
  }
  .timer-status {
    margin: 0;
    font-size: 1.05rem;
    font-weight: 700;
  }
  .timer-expected {
    margin: 0;
    font-family: var(--font-mono);
    font-size: clamp(1.5rem, 6vw, 2.2rem);
    font-weight: 700;
    color: var(--accent-strong);
  }
  .timer-expected-num {
    font-variant-numeric: tabular-nums;
  }
  .timer-target {
    margin: 0;
    font-size: 0.92rem;
  }
  .timer-rest {
    margin: 0;
    font-size: 1.05rem;
    font-weight: 700;
    color: var(--text-muted);
  }
  .timer-rest-num {
    font-family: var(--font-mono);
    font-variant-numeric: tabular-nums;
  }
  .phase-progress {
    width: 100%;
    height: 0.5rem;
    background: var(--surface-muted);
    border-radius: var(--radius);
    overflow: hidden;
  }
  .phase-progress-fill {
    height: 100%;
    background: var(--accent-strong);
    transition: width 200ms linear;
  }
  .phase-progress.phase-kind-wait .phase-progress-fill {
    background: var(--text-muted);
  }
  .pour-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .pour-row {
    display: grid;
    grid-template-columns: 4.5rem 1fr auto;
    gap: 8px;
    padding: 8px 10px;
    border: 1px solid var(--border);
    border-radius: var(--radius);
    align-items: center;
    font-size: 0.9rem;
  }
  .pour-row .grams {
    font-family: var(--font-mono);
    color: var(--accent-strong);
    font-weight: 700;
  }
  .pour-row .time-detail {
    display: block;
    margin-top: 2px;
    font-size: 0.8rem;
    color: var(--text-muted);
  }
  .pour-row.done {
    color: var(--text-muted);
    background: var(--surface-muted);
  }
  .pour-row.now {
    border-color: var(--accent);
    background: var(--accent-soft);
  }
  .sound-toggle {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 0.92rem;
    padding: 0 10px;
    min-height: 44px;
  }
  .sound-toggle input {
    accent-color: var(--accent);
    width: 18px;
    height: 18px;
  }
  ol {
    margin: 0;
    padding-left: 1.2rem;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
</style>
